[package]
name = "pybind11"
version = "2.11.1"

[source]
git = "https://github.com/pybind/pybind11.git"
tag = "v2.11.1"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
