[package]
name = "simdjson"
version = "3.6.2"

[source]
git = "https://github.com/simdjson/simdjson.git"
tag = "v3.6.2"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
