[package]
name = "boost"
version = "1.83.0"

[source]
git = "https://github.com/boostorg/boost.git"
tag = "boost-1.83.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
