[package]
name = "libgcrypt"
version = "libgcrypt-1.10.3"

[source]
git = "https://dev.gnupg.org/source/libgcrypt.git"
tag = "libgcrypt-1.10.3"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
