[package]
name = "range-v3"
version = "0.12.0"

[source]
git = "https://github.com/ericniebler/range-v3.git"
tag = "0.12.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
