[package]
name = "tl-optional"
version = "1.1.0"

[source]
git = "https://github.com/TartanLlama/optional.git"
tag = "v1.1.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
