[package]
name = "poco-util"
version = "1.12.4"

[source]
git = "https://github.com/pocoproject/poco.git"
tag = "poco-1.12.4"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
