[package]
name = "reflect-cpp"
version = "0.10.0"

[source]
git = "https://github.com/getml/reflect-cpp.git"
tag = "v0.10.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
