[package]
name = "rapidjson"
version = "1.0.1"

[source]
git = "https://github.com/Tencent/rapidjson.git"
tag = "v1.0.1"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
