[package]
name = "qhttpengine"
version = "0.1.0"

[source]
git = "https://github.com/nitroshare/qhttpengine.git"
tag = "0.1.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
