[package]
name = "benchmark"
version = "1.8.3"

[source]
git = "https://github.com/google/benchmark.git"
tag = "v1.8.3"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
