[package]
name = "sycl"
version = "sycl-nightly/20231115"

[source]
git = "https://github.com/intel/llvm.git"
tag = "sycl-nightly/20231115"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
