[package]
name = "nss"
version = "NSS.3.96.RTM"

[source]
git = "https://github.com/nss-dev/nss.git"
tag = "NSS_3_96_RTM"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
