[package]
name = "cpprestsdk"
version = "2.10.19"

[source]
git = "https://github.com/microsoft/cpprestsdk.git"
tag = "v2.10.19"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
