[package]
name = "cryptopp"
version = "CRYPTOPP.8.9.0"

[source]
git = "https://github.com/weidai11/cryptopp.git"
tag = "CRYPTOPP_8_9_0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
