[package]
name = "libcpio"
version = "3.7.0"

[source]
git = "https://github.com/libarchive/libarchive.git"
tag = "v3.7.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
