[package]
name = "googletest"
version = "1.12.1"

[source]
git = "https://github.com/google/googletest.git"
tag = "v1.12.1"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
