[package]
name = "celero"
version = "2.8.2"

[source]
git = "https://github.com/DigitalInBlue/Celero.git"
tag = "v2.8.2"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
