[package]
name = "cutelyst"
version = "3.3.0"

[source]
git = "https://github.com/cutelyst/cutelyst.git"
tag = "v3.3.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
