[package]
name = "cpp-httplib"
version = "0.14.1"

[source]
git = "https://github.com/yhirose/cpp-httplib.git"
tag = "v0.14.1"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
