[package]
name = "expected-lite"
version = "0.6.1"

[source]
git = "https://github.com/martinmoene/expected-lite.git"
tag = "v0.6.1"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
