[package]
name = "easyloggingpp"
version = "9.96.6"

[source]
git = "https://github.com/amrayn/easyloggingpp.git"
tag = "v9.96.6"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
