[package]
name = "allegro"
version = "5.2.7.0"

[source]
git = "https://github.com/liballeg/allegro5.git"
tag = "5.2.7.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
