[package]
name = "libclang"
version = "llvmorg-16.0.6"

[source]
git = "https://github.com/llvm/llvm-project.git"
tag = "llvmorg-16.0.6"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
