[package]
name = "argon2"
version = "20161029"

[source]
git = "https://github.com/P-H-C/phc-winner-argon2.git"
tag = "20161029"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
