[package]
name = "bzip2"
version = "bzip2-1.0.7"

[source]
git = "https://sourceware.org/git/bzip2.git"
tag = "bzip2-1.0.7"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
