[package]
name = "mpir"
version = "mpir-3.0.0"

[source]
git = "https://github.com/wbhart/mpir.git"
tag = "mpir-3.0.0"

[build]
system = "cmake"
args = ["-DBUILD_TESTING=OFF", "-DBUILD_EXAMPLES=OFF"]
